version: "3"

services:
   db:
      container_name: postgres_container
      image: postgres:15.2
      restart: always
      environment:
         POSTGRES_PASSWORD: abcd1234
         POSTGRES_USER: admin
         POSTGRES_DB: mydatabase
      ports:
         - "5432:5432"
      volumes:
         - ./data/postgres:/var/lib/postgresql/data
   adminer:
      image: adminer:4.8.1
      restart: always
      ports:
         - "8080:8080"
      depends_on:
         - db
      volumes:
         - ./data/adminer:/var/lib/adminer/data
